name: OWASP ZAP Security Scan

on:
  push:
    branches: [ "main", "feature/tags" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the Web Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.flipkart.com/ss-26-men-ub-at-store?pageUID=1784049157615' # Replace with your test/staging URL
          cmd_options: '-a' # Includes alpha passive scan rules (useful for modern auth patterns)
